### ISSUE TITLE
Starting up Chrome extension

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#1]
Expand *manifest.json* such that the extension shows *index.html* file (issue #2) when a newtab is opened.

**Comment by kaneki-ken260** [comment]
claim

**Comment by Kajal-7** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by criticic** [comment]
i think this is now up for claims, id like to claim it then

**Comment by rag-hav** [comment]
@kaneki-ken260 Time is up!

@criticic @Kajal-7 @codelord09 As per mentor guidelines, only claims made after removing the assignee will be considered. Also since manifest requirements have changed I will create a new issue for this all together.
