### ISSUE TITLE
Update Manifest.json

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#10]
Update the manifest.json such that the extension opens index.html on newtab page and has a background page called background.html, also create background.html and run the background.js script in it. Also add an icon to it (use dummy icon now, next issue will be for icon creation).

Skills - Rookie (plenty of tutorials available)

Note: Do not make unnecessary changes to the files, ensure that files are properly formatted. Write proper documentation.

Time limit - 1 day

**Comment by jalanprakhar** [comment]
claim
