### ISSUE TITLE
Notification and settings 

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#16]
Inside make timer text function (refer #7 ) add code to create notification according to `this.settings.get_int("notify-before")` using `Main` that has already been imported. Also add a seconds field to timerText accoding to `this.settings.get_boolean("show-seconds")`.

Time limit- 1 day

Bonus: Refactor the edge cases into a clean if-else ladder.

**Comment by rag-hav** [comment]
@Monik09 time's up!

**Comment by raghavgoel25** [comment]
CL

> @Monik09 time's up!

Claim
