### ISSUE TITLE
Cache file

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#24]
Search the gnome directory for `#5` and complete the function(s).

loadFromFile saveToFile

Use google and gnome documentation to learn how to read and open files using gnome libraries. You can also look at code from other gnome extensions (reccomended- random wallpaper extension). 

### Prerequisites to claim this issue
* Post a screenshot of your gnome installation to claim this issue.

Time limit: 2 days total. You also need to show that you have started work at the end of first day, by either created a pull request (even incomplete) or just pinging me on discord (zorian). Feel free to ask any doubts!

**Comment by karankc23** [comment]
Claim

**Comment by raghavgoel25** [comment]
claim

**Comment by shashwat-mittal** [comment]
claim

**Comment by rag-hav** [comment]
@shashwat-mittal Post a screenshot of your gnome installation to claim this issue.

**Comment by shashwat-mittal** [comment]
![Screenshot from 2021-10-09 13-23-27](https://user-images.githubusercontent.com/74846797/136649686-83193068-8077-4076-baac-a74c0cf9f40d.png)
claim

**Comment by karankc23** [comment]
![gnomeshell](https://user-images.githubusercontent.com/76587341/136976976-71952192-27d8-46b7-9e90-613a819e6cc1.png)
