### ISSUE TITLE
Make timer text

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#5]
Search the gnome directory for `#4` and complete the function.

_getTimerText

You have to use `this.contest.secondsTillNextContest` to make a string that displays the remaining time. Refer to screenshot.

**Comment by raghavgoel25** [comment]
claim

**Comment by bipulkmr-crypto** [comment]
claim

**Comment by codelord09** [comment]
claim

**Comment by shlesh** [comment]
claim

**Comment by codelord09** [comment]
claim
