### ISSUE TITLE
gnome 40.04 (expert level task)- change the prefs.js / schema.xml for gnome 40

### ISSUE THREAD

**Issue by rag-hav** [opencodeiiita/Contest-Countdown#81]
The current extension was developed for gnome 3.36 and contains many deprecated libraries. Due to them, the extension does not work properly in gnome 40.04.  In particular opening the settings gives an error like this.

The settings of extension contestcountdown@raghav had an error:
```
Error: No property margin on GtkGrid
Stack trace:
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
buildPrefsWidget@/home/raghav/.local/share/gnome-shell/extensions/contestcountdown@raghav/prefs.js:24:27
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Debug it so that settings can be opened.

### Claim by posting screenshot of gnome 40+ ( type `gnome-shell --version` in terminal and take a screenshot)

Note- This is a very difficult task that will require lots of googling and reading documentation. Based on the number of issues encountered, there is a chance of points of being increased.

**Comment by rushilpatra** [comment]
Claim

**Comment by rag-hav** [comment]
@anshg0711 post screenshot to claim :yawning_face:
